version: '3.8'
services:
  client:
    build: ./client
    container_name: client
    depends_on:
      - server
    networks: 
      - docker-network
  server:
    build: ./server
    container_name: server
    networks: 
      - docker-network
networks:
  docker-network:
    driver: bridge